### ISSUE TITLE
Needs contributors file, to-do's for contributors, clearer use-related info

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando/OAuth2-mock-play#1]
Intro part: add language to the effect of "this project aims to be useful to anyone who ..." + cite a few examples of how people would use it and (to) achieve X result (show it will make their life better/speed up their work/give them results they need). Also:
- describe how this project is similar to/different from any other existing projects, to help improve usability
- add to-do's to encourage contributions

**Comment by mdedetrich** [comment]
Have just merged a pull request to make things clearer + add some extra info. Let me know if the current README is good enough
